### PR TITLE
fix work dir env

### PR DESCRIPTION
**Pull request by bloodearnest**
- chore: fix docker-compose environment for WORK_DIR
- chore: make docker/Makefile able to run the prod docker image more easily

### CODE REVIEW

**Review by benbc — APPROVED** [review]
How much work would it be to change the directory name and env var to be consistent (that is, both either with or without the underscore)?

**Comment by bloodearnest** [comment]
> How much work would it be to change the directory name and env var to be consistent (that is, both either with or without the underscore)?

It's a 2 character change to change `WORK_DIR=/work_dir`. Job runner doesn't care about whatever WORK_DIR points to, so it's up to what we set it to in the docker-compose file really.

Changing it to `WORKDIR=/workdir` also simple, as we currently don't set WORK_DIR in backend-server or on TPP at all, we just use the default of `$PWD/workdir`.

But changing the default to be `$PWD/work_dir` would be effort, as we'd need to migrate

So, I think we want to change to `WORKDIR=/workdir`, and also support WORK_DIR as an alternative?

**Comment by benbc** [comment]
> I think we want to change to WORKDIR=/workdir

That sounds right.

> and also support WORK_DIR as an alternative?

I'm doubtful of the value of this if there aren't lots of places already using it. Better, I think, to make the effort to get everything straight and consistent now rather than allowing for later divergence and suprises (and a tiny bit of extra complexity handling both).

**Comment by bloodearnest** [comment]
Ok.

Will also change `config.WORK_DIR` to `config.WORKDIR` to match.

**Review by benbc — COMMENTED** [review]
I think maybe you've missed a `work_dir` in `docker/docker-compose.yaml`?

The second commit is a bit weird now, with the `Makefile` stuff alongside the work dir rename. Maybe just squash the whole thing into one commit?

**Comment by bloodearnest** [comment]
> I think maybe you've missed a `work_dir` in `docker/docker-compose.yaml`?

Ah, yes

> The second commit is a bit weird now, with the `Makefile` stuff alongside the work dir rename. Maybe just squash the whole thing into one commit?

d'oh, will fix

**Review by benbc — APPROVED** [review]

**Pull request merged**
